In [2]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
my_list

[1, 2, 3]

In [16]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,10,5000)

array([0.00000000e+00, 2.00040008e-03, 4.00080016e-03, ...,
       9.99599920e+00, 9.99799960e+00, 1.00000000e+01])

In [5]:
np.arange(0,13,4)

array([ 0,  4,  8, 12])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [10]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.full([2,4],-45)

array([[-45, -45, -45, -45],
       [-45, -45, -45, -45]])

### linspace
Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,1,10)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

Creates an identity matrix

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(5)
#values between 0 and 1

array([0.27301971, 0.0967285 , 0.84762956, 0.54291515, 0.6812381 ])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [12]:
np.randint(1,10,3)

AttributeError: module 'numpy' has no attribute 'randint'

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [50]:
np.random.randint(1,100)

44

In [22]:
arr1 = np.random.randint(1,100,50)
arr1

array([79, 19, 23, 79, 59, 28, 23, 58, 57, 97, 61, 40, 39,  8, 27, 35,  1,
       45, 25, 16, 17,  6, 50, 94,  2, 16, 42, 83, 52, 18, 32, 78, 95, 17,
       99, 91, 17, 84, 71, 38, 28, 73, 84, 54, 45, 27, 22,  7, 31, 28])

In [3]:
a = np.array(np.random.randint(2,10,(3,3)))
print(a)

[[3 8 6]
 [2 9 8]
 [3 9 6]]


In [4]:
a = np.array(np.random.randint(2,10,(3,3,3)))
print(a)

[[[2 3 8]
  [2 8 2]
  [4 4 9]]

 [[5 4 9]
  [7 8 4]
  [4 7 8]]

 [[3 5 6]
  [3 7 3]
  [6 9 2]]]


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [9]:
arr1 = np.random.randint(0,50,10)
arr1

array([20, 27, 16,  2, 33, 43,  2,  8, 45, 34])

In [6]:
arr = np.arange(25)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [14]:
import numpy as np
a = np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.

In [54]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
a=np.random.randint(0,1000,500)
a

array([140, 460, 170, 604,  20, 372, 151, 758, 260, 545, 195, 853, 555,
       903,  34, 700, 203, 340, 370, 127, 520, 681, 683, 452, 533, 578,
       614, 860, 557, 779, 260, 643,  11, 315,  78, 288, 144,  64, 339,
       738, 880, 478, 226, 952,   0, 561, 552, 476, 732, 259, 611, 265,
       185, 954, 877, 888, 513, 253, 985, 339, 689, 868, 122, 166, 541,
       498, 774, 891, 734, 884, 986,  83, 524, 932, 180, 839, 170, 920,
       400, 712, 883, 503, 145, 929, 224, 988, 667, 454, 505, 304, 965,
       500, 375, 950, 825, 432, 880, 538, 369, 770, 421, 776, 262,  78,
       137, 327, 250, 738, 767, 294,   1, 298, 927, 322, 869, 225, 796,
       340, 282, 955, 994, 367, 256, 719, 556,  13, 868, 969, 337, 434,
       822, 375, 426,  24, 783, 924, 682, 394, 973, 730, 343, 331, 631,
        54, 750, 349, 620, 219, 130, 719, 584, 524, 251, 328, 421, 802,
       774, 325, 889, 563, 539, 711, 989,  73, 696, 686, 716, 198, 140,
       985, 209, 868, 538, 149, 122, 367, 261, 864, 380, 604, 61

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [10]:
arr1

array([20, 27, 16,  2, 33, 43,  2,  8, 45, 34])

In [17]:
a.max()

994

In [18]:
a.argmax()

120

In [19]:
a.min()

0

In [20]:
a.argmin()

44

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [25]:
arr1.reshape(5,10)

array([[79, 19, 23, 79, 59, 28, 23, 58, 57, 97],
       [61, 40, 39,  8, 27, 35,  1, 45, 25, 16],
       [17,  6, 50, 94,  2, 16, 42, 83, 52, 18],
       [32, 78, 95, 17, 99, 91, 17, 84, 71, 38],
       [28, 73, 84, 54, 45, 27, 22,  7, 31, 28]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')