In [1]:
2+2

4

In [2]:
2*2

4

In [4]:
2**3

8

In [5]:
a = 2
b= 5
c = a+b
print(c)

7


In [6]:
a = 'hello'
b ="hello"
c = '''hello
welcome
to
python'''

In [7]:
print('text here')

text here


In [8]:
input('enter a number')

enter a number3


'3'

In [21]:
a = [1,2,3,4,5,6,7,8,9]


In [10]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
a[5]

6

In [12]:
a[-1]

9

In [13]:
a[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
a[2:]

[3, 4, 5, 6, 7, 8, 9]

In [15]:
a[:-2]

[1, 2, 3, 4, 5, 6, 7]

In [22]:
a[::2]

[1, 3, 5, 7, 9]

In [18]:
a = 'python is cool'

In [20]:
a[::-2]

'lo inhy'

In [28]:
x = 5
if (x>6):
    print('false')
elif (x==5):
    print('hi')
    
else:
    print('true')

hi


In [32]:
loc='bank'
balance=100000
welcome = input('where do you want to go: bank , restaurant or home ')


if(welcome=='bank'):
    print('welcome to bank')
    loan = input('do you need a loan ?')
    if(loan=='yes'):
        loan_amt = int(input('enter amount '))
        if(loan_amt < balance):
            print('loan approved ')
        else:
            print('insufficient balance ')
    else:
        print('Thank you ')
    
elif(welcome=='restaurant'):
    print('welcome to restaurant')
else:
    print('welcome to home')

where do you want to go: bank , restaurant or home restaurant
welcome to restaurant


In [1]:
import numpy as np

In [11]:
x = [[1],[4], [4]]
np.array(x)


array([[1],
       [4],
       [4]])

In [13]:
x = 
np.array(x)


5,9,6


ValueError: invalid literal for int() with base 10: '5,9,6'

In [ ]:
for loop, 

In [14]:
import numpy as np

# 

In [16]:
l1 = [5,6,9,8,6]
np.array(l1)

array([5, 6, 9, 8, 6])

In [19]:
l2 = [[5,6,9],[4,3,6]]
np.array(l2)

array([[5, 6, 9],
       [4, 3, 6]])

In [21]:
for x in range(0,4):
    print('hi')

hi
hi
hi
hi


In [ ]:
now given a list, find the square of all of its elements

In [ ]:
li = [5,1,2,3,4,8,7,9,3]

In [23]:
a = [5,6,9,3,54,63,25,1,4,75]

sq = [num**2 for num in a]
print(sq)

[25, 36, 81, 9, 2916, 3969, 625, 1, 16, 5625]
